spring:
  application:
    name: repository
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/resto
    username: postgres
    password: adminadmin
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: create-drop